# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

source: ./
destination: _site
sass:
  sass_dir: _sass
  style: expanded # compressed # expanded

# permalink and highlighter
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

# SEO settings
title: "Watch M.E."
description: "Activity Trackers for Medical Emergencies"
keywords: "activity, fitness, tracker, medical, emergency, startup, wearables, heart, attack, stroke"

# Site settings
url: https://watchme.org.uk/
baseurl: ""
# baseurl: ""

# Author settings
author:
  name      : Watch M.E.
  job       : Activity Trackers for Medical Emergencies
  bio       : "Activity Trackers for Medical Emergencies"
  thumb     : /images/author.jpg
  # email     : hannah@watchme.org.uk
  url       : https://watchme.org.uk/
  github    : https://github.com/watch-m-e
  # twitter   : http://twitter.com/nandomoreirame
  # facebook  : http://facebook.com/fernando.dev
  # linkedin  : http://linkedin.com/in/nandomoreirame

# google_analytics: UA-52446115-1
repo: https://github.com/watch-m-e/watch-m-e

# comments
# disqus_shortname: "fernandomoreira"
